# Generated by Django 4.0.4 on 2022-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='romm_main_user',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
