# Generated by Django 4.0.4 on 2022-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_romm_main_user_room_room_main_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_main_user',
            field=models.IntegerField(max_length=150),
        ),
    ]
