# Generated by Django 4.0.4 on 2022-07-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_room_room_main_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_main_user',
            new_name='super_user',
        ),
    ]
