# Generated by Django 4.0.4 on 2022-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_room_main_user_room_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='super_user',
            field=models.CharField(max_length=150),
        ),
    ]
