# Generated by Django 4.0.4 on 2022-07-14 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_alter_room_super_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel_name', models.CharField(max_length=150, unique=True)),
                ('user', models.ManyToManyField(related_name='user_channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
