# Generated by Django 4.0.4 on 2022-07-14 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_channel_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_names',
            name='user',
        ),
        migrations.AlterField(
            model_name='channel_names',
            name='Channel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
