# Generated by Django 4.0.4 on 2022-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_channel_names_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_names',
            name='room_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
