# Generated by Django 4.0.4 on 2022-07-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_channel_names_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel_names',
            old_name='room_name',
            new_name='user_name',
        ),
    ]
