# Generated by Django 4.0.4 on 2022-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_rename_room_name_channel_names_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_names',
            name='Channel_name',
            field=models.CharField(max_length=150),
        ),
    ]
